site_name: Backpack Hero Modding
extra_css: [assets/style.css]


nav:
  - Home: index.md
  - Installing Mods: Installing Mods.md
  - Creating Mods: How_to_Create_Mods
  - JSON Reference:
    - JSON_Reference/Modpack.md
    - Items: 
      - JSON_Reference/Items/index.md
      - JSON_Reference/Items/
    - Enums: JSON_Reference/Enums/
    - Misc: JSON_Reference/Misc/

plugins:
  - search
  - include_dir_to_nav:
      file_pattern: '^(?!index\.md$|Item\.md$).*\.md$'

theme:
  name: material
  logo: assets/logo.png
  favicon: assets/favicon.ico
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  
   # primary: red
  features:
   # - navigation.instant
    - navigation.indexes
    - navigation.sections
   # - navigation.expand
    - navigation.top
    - toc.integrate

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true 

